# Generated by Django 5.2.3 on 2025-06-29 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artworks',
            old_name='user_id',
            new_name='user',
        ),
    ]
