# Generated by Django 5.2.3 on 2025-06-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_rename_user_id_artworks_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artworks',
            table='artworks',
        ),
    ]
