# Generated by Django 5.2.3 on 2025-06-29 21:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_alter_artworks_table'),
        ('likes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('user', 'artwork')},
        ),
        migrations.AlterModelTable(
            name='likes',
            table='likes',
        ),
    ]
